### ISSUE TITLE
Badges where points >= 2 not assigned to users 

### ISSUE THREAD

**Issue by CyrilBlankaert** [qcod/laravel-gamify#11]
I started using this package and when i create a badge and assign the points to the user it does not create or assign the badge to the user ( Like #9 )

php artisan cache:clear and php artisan cache:forget gamify.badges.all doesn't resolve the problem !

In database, user_badges table result (user_id, badge_id) is not added when I reached the second badge (2 points, the first badge is only 1 point)

I would like to have :

user_id 1 badge_id 1
user_id 1 badge_id 2
is it possible ?

Thanks for help !

**Comment by saqueib** [comment]
Share your badge class so I can look into this

**Comment by CyrilBlankaert** [comment]
First badge (1 point) 

```
<?php

namespace App\Gamify\Badges;

use QCod\Gamify\BadgeType;

class FirstBadge extends BadgeType
{
    /**
``     * Description for badge
     *
     * @var string
     */
    protected $description = '';

    /**
     * Check is user qualifies for badge
     *
     * @param $user
     * @return bool
     */
    public function qualifier($user)
    {
        return $user->getPoints() >= 1;
    }
}
```

Second badge :  (2 points)

```

<?php

namespace App\Gamify\Badges;

use QCod\Gamify\BadgeType;

class SecondBadge extends BadgeType
{
    /**
     * Description for badge
     *
     * @var string
     */
    protected $description = '';

    /**
     * Check is user qualifies for badge
     *
     * @param $user
     * @return bool
     */
    public function qualifier($user)
    {
        return $user->getPoints() >= 2;
    } 
}
```

**Comment by CyrilBlankaert** [comment]
When does the badge is passed to the Database ? 

The query seems to be not « activated » When user has 2 points

**Comment by saqueib** [comment]
can you confirm you see the `FirstBadge` and `SecondBadge` in `badges` table. if not run `php artisan cache:clear` and give user point to trigger the sync.

**Comment by CyrilBlankaert** [comment]
SecondBadge is not created in table! 
I have to add it manually ... it’s a problem.

**Comment by CyrilBlankaert** [comment]
Badges are in database table sometimes ! It seems there is a problem with my cache and I don't know how to resolve it ?
