### ISSUE TITLE
subject for reputation

### ISSUE THREAD

**Issue by marvelbark2** [qcod/laravel-gamify#13]
Hello
Please how to add a dynamic subject like , the user X created the  post Y ?

And thanks

**Comment by saqueib** [comment]
If you want to print history of reputation you can just use this and build the dynamic msg https://github.com/qcod/laravel-gamify#get-reputation-history

```php
foreach($user->reputations as $reputation) {
    echo 'user '. $reputation->payee->name . ' created  post ' . $reputation->subject->title;
}
```

Please explain more if I miss understood your issue.

**Comment by marvelbark2** [comment]
Just how to add subject text because in my db i have subject empty (NULL)

**Comment by saqueib** [comment]
Ok, share your subject model and point type which is giving you `null` subject. What about `subject_id`, does that has value?  You should add this relation on the subject model 

```php
 /**
     * Get all the post's reputation.
     */
    public function reputations()
    {
        return $this->morphMany('QCod\Gamify\Reputation', 'subject');
    }
```
