### ISSUE TITLE
Class 'QCod\Gamify\GamifyServiceProvider' not found"

### ISSUE THREAD

**Issue by ojhadiwesh** [qcod/laravel-gamify#15]
I am getting this error, I have installed the package. 

app.php constains "QCod\Gamify\GamifyServiceProvider::class"

composer.json contains  "qcod/laravel-gamify": "^1.0",

Any idea how to solve this?

**Comment by saqueib** [comment]
which version of Laravel you are using?

**Comment by ojhadiwesh** [comment]
I am using the 5.8 version. I tried adding the service provider in the app.php, still doesnt work
.

**Comment by saqueib** [comment]
I just created a fresh app with Laravel 5.8 and then ran

```
composer require qcod/laravel-gamify
```

I don't see any issue it's working fine. 

Please run `composer dump-autoload` 
and lastly, if it didnt work then
remove the `vendor` folder and `composer.lock` and run `composer install`
