### ISSUE TITLE
I always get this error while i'm trying to give the points to the user

### ISSUE THREAD

**Issue by Ndottens** [qcod/laravel-gamify#29]
QCod\Gamify\Exceptions\InvalidPayeeModel
payee() method must return a model which will get the points.

**Comment by Ndottens** [comment]
Sorry for creating an issue found the problem by my self

**Comment by sahrialardians** [comment]
Hi @Ndottens 

What is your problem? How do you solve this problem? because I also have this problem.

Thank you
