### ISSUE TITLE
Feature: Morph support for Payee

### ISSUE THREAD

**Issue by hasnatbabur** [qcod/laravel-gamify#32]
Thanks a lot for such awesome plugin. I feel it will be a breaking change but having ability to use badges for other models such as admins, groups, vendors, organizations etc. along with user model will be a huge benefit. Like this feature "Many To Many (Polymorphic)" (https://laravel.com/docs/6.x/eloquent-relationships#polymorphic-relationships). Thanks

**Comment by saqueib** [comment]
I will look into this if I can pull this off without breaking changes

**Comment by Necmttn** [comment]
Any update on this? 
I wanna have users and teams have reputations separate from each other. not sure how to do it?
