### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by TechTailor** [qcod/laravel-gamify#33]
Hey, 

Just came across this package and it looks promising but wanted to know if its still being maintained by the author since there are a few pr's and issues unanswered.

Would love to use it in one of my projects if it is.

Thanks.

**Comment by saqueib** [comment]
@TechTailor I am currently not adding features to this but it's maintained and will get new laravel versions support

**Comment by felix2056** [comment]
So far it's working really well in the latest version of Laravel
