### ISSUE TITLE
undoPoint() doesn't seem to work for me

### ISSUE THREAD

**Issue by seanhudson** [qcod/laravel-gamify#5]
`undoPoint(new PostCreated($post));`

doesn't do anything. Am I missing something? I ended up creating another PointType class to just add negative points. However, it seems like I may be missing something. It would be nice to use the helper functions you created.

**Comment by saqueib** [comment]
In order to undo a point you must be given point on the same model, also you need to pass the second argument with the user if you are not logged in.

```
undoPoint(new PostCreated($post, $post->user));
```

please share some more code if it does'nt help.
