### ISSUE TITLE
install on laravel 5.8.4

### ISSUE THREAD

**Issue by wa7eedem** [qcod/laravel-gamify#6]
hi ,
I couldn't install the package on laravel 5.8.4

my composer : `"laravel/framework": "~5.8.0",`

I try it with :  `"laravel/framework": "5.8.*",`

I got : 

` Problem 1
    - Installation request for qcod/laravel-gamify ^1.0 -> satisfiable by qcod/laravel-gamify[1.0.0].
    - Conclusion: remove laravel/framework v5.8.4
    - Conclusion: don't install laravel/framework v5.8.4
    - qcod/laravel-gamify 1.0.0 requires laravel/framework ~5.4.0|~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.4.x-dev, v5.8.4].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.8.4].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.8.4].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.8.4].
    - Installation request for laravel/framework (locked at v5.8.4, required as ~5.8.0) -> satisfiable by laravel/framework[v5.8.4].`

**Comment by saqueib** [comment]
@wa7eedem Its now compatible with L5.8 version `1.0.1`
