### ISSUE TITLE
Is there a limit on the number? allowDuplicates

### ISSUE THREAD

**Issue by zhaomengqiao** [qcod/laravel-gamify#8]
Is there a limit on the number?For example, posting 3 times a day

**Comment by saqueib** [comment]
You should use qualifier function on a point type to decide when you want to allow points to be given.

public function qualifier()
    {
        // check if already given points 3 time in same day
    }

**Comment by saqueib** [comment]
You should use qualifier function on a point type to decide when you want to allow points to be given.

public function qualifier()
    {
        // check if already given points 3 time in same day
    }

**Comment by zhaomengqiao** [comment]
thank you
